import StyleProvider from '@/components/Providers/StyleProvider';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import NextAuthProvider from '@/components/Providers/NextAuthProvider';
import { getCurrentUser } from '@/lib/session';
const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const user = await getCurrentUser();
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <NextAuthProvider>
                    <StyleProvider>{children}</StyleProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}
