import type { Metadata } from 'next';

import { Montserrat } from 'next/font/google';
import { getCurrentUser } from '@/lib/session';

const montserrat = Montserrat({ subsets: ['latin'] });

import { ThemeProvider } from '@/lib/providers/theme';
import AuthProvider from '@/lib/auth/providers';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <AuthProvider>
                    <ThemeProvider>{children}</ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
